@baseurl = http://api.whabit.wode.lh

###
PUT {{baseurl}}/session/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "id": "3",
    "secret": "oEsDIJcgiHpLuM6jnfOgxxiaPQuXXtW1qfOGL7DP",
    "email": "teste3@teste.com",
    "password": "password"
}

###
POST {{baseurl}}/user HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "teste",
    "email": "teste3@teste.com",
    "password": "password"
}
