@baseurl = http://api.whabit.wode.lh

GET {{baseurl}}/habit HTTP/1.1

###
GET {{baseurl}}/habit/2 HTTP/1.1

###
GET {{baseurl}}/habit/2/accomplishments?year=2019 HTTP/1.1
Content-Type: application/json

###
POST {{baseurl}}/habit HTTP/1.1
content-type: application/json

{
    "name": "New Habit"
}

###
GET {{baseurl}}/accomplishment HTTP/1.1

###
POST {{baseurl}}/habit/1/accomplishments?year=2020&month=1&day=1

###
DELETE {{baseurl}}/habit/1/accomplishments?year=2020&month=1&day=1
